name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: install
         uses: actions/upload-artifact@v3
         run: bash install.sh
         with:
           name: build
           path: build
