name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: install
         run: bash install.sh
       - name: test
         run: bash test.sh
       - name: upload
         if: always()
         uses: actions/upload-artifact@v3
         with:
           name: build
           path: build
